auth:
  jwt:
    refreshing:
      expirationMinutes: 120
      secret: secret1
    access:
      expirationMinutes: 5
      secret: secret2
      requireNotExpired: false

app:
  api-user:
    name: user
    hashedPassword: $2a$10$Luy5a.WpjHIkLy59SjmLkuR88oDdLbvkFbJ.pKC2u0KK1bnwSJuna
  swagger-user:
    name: swaggerUser
    hashedPassword: $2a$10$Luy5a.WpjHIkLy59SjmLkuR88oDdLbvkFbJ.pKC2u0KK1bnwSJuna
  url: http://localhost:8889

server:
  port: 8889