auth:
  jwt:
    refreshing:
      expirationMinutes: 120
      secret: secret1
    access:
      expirationMinutes: 5
      secret: secret2
      requireNotExpired: false
      #requireNotExpired currently not used, may correspond to a different approach to token generation

app:
  api-user:
    name: RegularClicker
    hashedPassword: $2a$10$Luy5a.WpjHIkLy59SjmLkuR88oDdLbvkFbJ.pKC2u0KK1bnwSJuna
  api-user_admin:
    name: MasterOfInterface
    hashedPassword: $2a$10$Luy5a.WpjHIkLy59SjmLkuR88oDdLbvkFbJ.pKC2u0KK1bnwSJuna
  swagger-user:
    name: swaggerUser
    hashedPassword: $2a$10$Luy5a.WpjHIkLy59SjmLkuR88oDdLbvkFbJ.pKC2u0KK1bnwSJuna
  url: https://api.major.ovh:28889

server:
  port: 8889